### ISSUE TITLE
Error thrown when opening/closing chest

### ISSUE THREAD

**Issue by jayofearth** [Redned235/PhatLoots#46]
1.19.2 Spiggot / Multiverse 4.3.1

Setting up the plugin for the first time and noticed that no loot is dropping and this error pops up in the console.

17.12 01:20:08 [Server] Server thread/ERROR Could not pass event InventoryCloseEvent to PhatLoots v5.4.2
17.12 01:20:08 [Server] INFO org.bukkit.event.EventException: null
17.12 01:20:08 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
17.12 01:20:08 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
17.12 01:20:08 [Server] INFO at net.tonimatasdev.perworldplugins.listener.RegisteredListener.callEvent(RegisteredListener.java:18) ~[?:?]
17.12 01:20:08 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
17.12 01:20:08 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
17.12 01:20:08 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1384) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3597-Spigot-4aa5ead-aaf484f]
17.12 01:20:08 [Server] INFO at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2640) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3597-Spigot-4aa5ead-aaf484f]
17.12 01:20:08 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1226) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3597-Spigot-4aa5ead-aaf484f]
17.12 01:20:08 [Server] INFO at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:1387) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3597-Spigot-4aa5ead-aaf484f]
17.12 01:20:08 [Server] INFO at net.minecraft.world.level.block.BlockChest.a(BlockChest.java:269) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3597-Spigot-4aa5ead-aaf484f]
17.12 01:20:08 [Server] INFO at net.minecraft.world.level.block.state.BlockBase$BlockData.a(BlockBase.java:949) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3597-Spigot-4aa5ead-aaf484f]
17.12 01:20:08 [Server] INFO at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:531) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3597-Spigot-4aa5ead-aaf484f]
17.12 01:20:08 [Server] INFO at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1650) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3597-Spigot-4aa5ead-aaf484f]
17.12 01:20:08 [Server] INFO at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3597-Spigot-4aa5ead-aaf484f]
17.12 01:20:08 [Server] INFO at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3597-Spigot-4aa5ead-aaf484f]
17.12 01:20:08 [Server] INFO at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3597-Spigot-4aa5ead-aaf484f]
17.12 01:20:08 [Server] INFO at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3597-Spigot-4aa5ead-aaf484f]
17.12 01:20:08 [Server] INFO at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3597-Spigot-4aa5ead-aaf484f]
17.12 01:20:08 [Server] INFO at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3597-Spigot-4aa5ead-aaf484f]
17.12 01:20:08 [Server] INFO at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3597-Spigot-4aa5ead-aaf484f]
17.12 01:20:08 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3597-Spigot-4aa5ead-aaf484f]
17.12 01:20:08 [Server] INFO at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3597-Spigot-4aa5ead-aaf484f]
17.12 01:20:08 [Server] INFO at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3597-Spigot-4aa5ead-aaf484f]
17.12 01:20:08 [Server] INFO at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3597-Spigot-4aa5ead-aaf484f]
17.12 01:20:08 [Server] INFO at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3597-Spigot-4aa5ead-aaf484f]
17.12 01:20:08 [Server] INFO at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1106) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3597-Spigot-4aa5ead-aaf484f]
17.12 01:20:08 [Server] INFO at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1017) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3597-Spigot-4aa5ead-aaf484f]
17.12 01:20:08 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3597-Spigot-4aa5ead-aaf484f]
17.12 01:20:08 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?]
17.12 01:20:08 [Server] INFO Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "obj" is null
17.12 01:20:08 [Server] INFO at com.codisimus.plugins.phatloots.ChestAnimations.invokeMethod(ChestAnimations.java:89) ~[?:?]
17.12 01:20:08 [Server] INFO at com.codisimus.plugins.phatloots.ChestAnimations.playChestAction(ChestAnimations.java:60) ~[?:?]
17.12 01:20:08 [Server] INFO at com.codisimus.plugins.phatloots.ChestAnimations.closeChest(ChestAnimations.java:30) ~[?:?]
17.12 01:20:08 [Server] INFO at com.codisimus.plugins.phatloots.PhatLootChest.closeInventory(PhatLootChest.java:566) ~[?:?]
17.12 01:20:08 [Server] INFO at com.codisimus.plugins.phatloots.listeners.PhatLootsListener.onPlayerCloseChest(PhatLootsListener.java:72) ~[?:?]
17.12 01:20:08 [Server] INFO at jdk.internal.reflect.GeneratedMethodAccessor127.invoke(Unknown Source) ~[?:?]
17.12 01:20:08 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
17.12 01:20:08 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
17.12 01:20:08 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
17.12 01:20:08 [Server] INFO ... 28 more

**Comment by ShiftingKill** [comment]
What version of PhatLoots? The source code doesn't have much at these lines so if on 1.19.2 use the 1.19.2 build on the GitHub [here](https://github.com/Redned235/PhatLoots/releases/tag/v5.5.5)

**Comment by jayofearth** [comment]
Ah. My apologies, 5.4.2. I'll update.
