### ISSUE TITLE
Phatloots 5.5.7 does not work in 1.20.6/1.21 although it starts without errors

### ISSUE THREAD

**Issue by Chevels** [Redned235/PhatLoots#52]
On Modrinth I downloaded the version of Phatloots uploaded by Redned235 3 days ago for versions 1.20-1.21 of Minecraft.
I tested this version 5.5.7 on my pre-production server in 1.20.6 under Java 21 (without any other plugin):
- Phatloots starts without errors
- Commands work correctly in game except `/loot reset`
- `/loot gui [LootTableName]` => the interface works correctly
- `/loot give [playerName] [LootTableName]` => we correctly see the inventory that opens and we can collect the loot as expected.
- droppers & barrels linked to the loot table work correctly and send loot correctly

However:
- Linked chests on a loot table do not display any contents when opened. Sometimes we see the name of the chest for 1/10 of a second before giving way to empty contents.
At this point this generates an error in the console:
[https://pastebin.com/C8Yur0Eu](https://pastebin.com/C8Yur0Eu)

- Dispensers do not work at all and do not provide any loot
- `/loot reset` when targeting a container linked to a loot table no longer works and displays the message: "Target Air have been reset" (the command works correctly if you give the name of a table, but you can no longer reset only a specific chest...)

I report this problem hoping that these issues will be corrected because Phatloots deserves to be maintained because it is so great :)

Have a nice week-end !

**Comment by Redned235** [comment]
This is now resolved. Thanks for reporting!
