### ISSUE TITLE
Phatloots 5.5.6 doesn't work in 1.18.2

### ISSUE THREAD

**Issue by m-xxkong** [Redned235/PhatLoots#59]
I downloaded Phatloots 5.5.6 on Github for versions 1.13-1.19 of Minecraft.I used it on my server in 1.18.2 with another plugin:EssentialsX.
Commands and GUI work correctly.Config files can also be used.
However, when I used the/loot reload command,the items in the loot table had disappeared.If I create a collection in the loot table,the items in it,the items in the collection will also disappear.
I tried to change the config`AutoSavePeriod`.I hoped it worked.But it didn't.
I change the version of Phatloots and restart the server,but none of them can work.
I reported this issue because it is currently the best plugin for me, and I hope it can be fixed as soon as possible:D

**Comment by Redned235** [comment]
This version is no longer supported.

**Comment by m-xxkong** [comment]
> This version is no longer supported.

How can I use this plugin on 1.18.2?
